# Generated by Django 4.1.4 on 2023-01-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_vote_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='username',
        ),
    ]
