# Generated by Django 4.1.4 on 2023-01-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_feed_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
    ]
