# Generated by Django 4.1.4 on 2023-01-26 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0006_remove_poll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_reposted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feed', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feed.feed')),
            ],
        ),
    ]
