# Generated by Django 4.1.4 on 2023-01-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_feed_is_reposted_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='feed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='repost', to='feed.feed'),
        ),
    ]
