# Generated by Django 4.1.4 on 2023-01-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_repost_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedcomments',
            name='username',
        ),
    ]
