# Generated by Django 4.1.4 on 2023-01-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_feed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='is_reposted',
        ),
    ]
